using Visor.Core;
using Visor.IntegrationTests.MsSql.Stabs;
using Visor.SqlServer;
using Xunit;

namespace Visor.IntegrationTests.MsSql
{
    public class MsSqlRealDbTests
    {
        private const string ConnectionString = "Server=localhost,1433;Database=VisorTestDb;User Id=sa;Password=VisorStrongPass123!;TrustServerCertificate=True;";

        [Fact]
        public async Task Ms_FullFlow_Test()
        {
            // Arrange
            IVisorConnectionFactory factory = new SqlServerConnectionFactory(ConnectionString);
            var repo = new MsUserRepository(factory); // This class is generated by Visor.

            // Act & Assert: Scalar read
            var countBefore = await repo.GetCount();
            Assert.True(countBefore >= 0);

            // Act: Insert using a Table-Valued Parameter.
            var newUsers = new List<MsUserTvp>
            {
                new() { Name = "Visor User 1" },
                new() { Name = "Visor User 2" },
                new() { Name = "Visor User 3" } // The ID is not needed as it's an IDENTITY column in the database.
            };

            await repo.ImportUsers(newUsers);

            // Assert: Verify insertion and list mapping.
            var countAfter = await repo.GetCount();
            Assert.Equal(countBefore + 3, countAfter);

            var allUsers = await repo.GetAll(false);
            Assert.Contains(allUsers, u => u.Name == "Visor User 1");
        }
    }
}
