using Visor.Core;
using Visor.IntegrationTests.MsSql.Stabs;
using Visor.SqlServer;
using Xunit;

namespace Visor.IntegrationTests.MsSql;

public class MsSqlRealDbTests
{
    private const string ConnectionString = "Server=localhost,1433;Database=VisorTestDb;User Id=sa;Password=VisorStrongPass123!;TrustServerCertificate=True;";

    [Fact]
    public async Task Ms_FullFlow_Test()
    {
        // Arrange
        IVisorConnectionFactory factory = new SqlServerConnectionFactory(ConnectionString);
        var repository = new MsUserRepository(factory); // This class is generated by Visor.

        // Act & Assert: Scalar read
        var countBefore = await repository.GetCount();
        Assert.True(countBefore >= 0);

        // Act: Insert using a Table-Valued Parameter.
        var newUsers = new List<MsUserTvp>
        {
            new() { Name = "Visor User 1" },
            new() { Name = "Visor User 2" },
            new() { Name = "Visor User 3" } // The ID is not needed as it's an IDENTITY column in the database.
        };

        await repository.ImportUsers(newUsers);

        // Assert: Verify insertion and list mapping.
        var countAfter = await repository.GetCount();
        Assert.Equal(countBefore + 3, countAfter);

        var allUsers = await repository.GetAll(false);
        Assert.Contains(allUsers, u => u.Name == "Visor User 1");
    }
    
    [Fact] 
    public async Task ComplexFlow_ShouldReturn_ResultSet_Output_And_ReturnValue()
    {
        // Arrange
        var factory = new SqlServerConnectionFactory(ConnectionString);
        var repo = new MsComplexRepository(factory);

        // Act
        // В SQL: LIKE '' + '%' -> get all
        var result = await repo.GetUsersAsync("");

        // Assert
    
        // 1. Result Set (list)
        Assert.NotNull(result.Users);
        Assert.NotEmpty(result.Users);
        Assert.Equal(4, result.Users.Count); // Alice, Bob, Charlie, Dave
        Assert.Contains(result.Users, u => u.Name == "Alice");

        // 2. Output Parameter (@TotalRows)
        Assert.Equal(4, result.TotalCount);

        // 3. Return Value (RETURN 0)
        Assert.Equal(0, result.StatusCode);
    }
}
